// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projekt2.Data;

#nullable disable

namespace Projekt2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250513123025_CountDostawy")]
    partial class CountDostawy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Projekt2.Models.Dostawcy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Addres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ilosc_ha_pola")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nr_tel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dostawcy");
                });

            modelBuilder.Entity("Projekt2.Models.Dostawy", b =>
                {
                    b.Property<int>("Id_dostawy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_dostawy"));

                    b.Property<DateTime>("Data_dostawy")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DostawcaId")
                        .HasColumnType("int");

                    b.Property<int>("Id_dostawcy")
                        .HasColumnType("int");

                    b.Property<int>("Ilosc_towaru")
                        .HasColumnType("int");

                    b.HasKey("Id_dostawy");

                    b.HasIndex("DostawcaId");

                    b.ToTable("Dostawy");
                });

            modelBuilder.Entity("Projekt2.Models.Dzialy", b =>
                {
                    b.Property<int>("Id_dzialu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_dzialu"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_dzialu");

                    b.ToTable("Dzialy");
                });

            modelBuilder.Entity("Projekt2.Models.Kupcy", b =>
                {
                    b.Property<int>("Id_kupca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_kupca"));

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nr_tel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_kupca");

                    b.ToTable("Kupcy");
                });

            modelBuilder.Entity("Projekt2.Models.Magazyn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data_operacji")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_operacji")
                        .HasColumnType("int");

                    b.Property<int>("Ilosc_opakowan")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Magazyn");
                });

            modelBuilder.Entity("Projekt2.Models.Magazyn_sprzedarz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Id_operacji")
                        .HasColumnType("int");

                    b.Property<int>("Id_transakcji")
                        .HasColumnType("int");

                    b.Property<int>("Ilosc_opakowan_sprzedanych")
                        .HasColumnType("int");

                    b.Property<int>("OperacjaId")
                        .HasColumnType("int");

                    b.Property<int?>("TransakcjaId_transakcji")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OperacjaId");

                    b.HasIndex("TransakcjaId_transakcji");

                    b.ToTable("Magazyn_sprzedarz");
                });

            modelBuilder.Entity("Projekt2.Models.Pakownia", b =>
                {
                    b.Property<int>("Id_partii")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_partii"));

                    b.Property<DateTime>("Data_zmiany")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_kierownika_zmiany")
                        .HasColumnType("int");

                    b.Property<int>("Ilosc_towaru_wejscowego")
                        .HasColumnType("int");

                    b.Property<int>("Ilosc_towaru_wyjscowego")
                        .HasColumnType("int");

                    b.Property<int?>("Kierownik_zmianyId")
                        .HasColumnType("int");

                    b.HasKey("Id_partii");

                    b.HasIndex("Kierownik_zmianyId");

                    b.ToTable("Pakownia");
                });

            modelBuilder.Entity("Projekt2.Models.Plac_buraczany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data_operacji")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_dostawy")
                        .HasColumnType("int");

                    b.Property<int>("Ilosc_burakow")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Plac_buraczany");
                });

            modelBuilder.Entity("Projekt2.Models.Plac_produktownia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data_pobrania")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_dostawy")
                        .HasColumnType("int");

                    b.Property<int>("Id_partii")
                        .HasColumnType("int");

                    b.Property<int>("Ilosc_burakow_pobrana")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Plac_produktownia");
                });

            modelBuilder.Entity("Projekt2.Models.Pracownicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Addres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DzialId_dzialu")
                        .HasColumnType("int");

                    b.Property<int>("Id_dzialu")
                        .HasColumnType("int");

                    b.Property<int>("Id_stanowiska")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nr_tel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StanowiskoId_stanowiska")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DzialId_dzialu");

                    b.HasIndex("StanowiskoId_stanowiska");

                    b.ToTable("Pracownicy");
                });

            modelBuilder.Entity("Projekt2.Models.Produktownia", b =>
                {
                    b.Property<int>("Id_partii")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_partii"));

                    b.Property<DateTime>("Data_zmiany")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_kierownika_zmiany")
                        .HasColumnType("int");

                    b.Property<int>("Ilosc_towaru_wejscowego")
                        .HasColumnType("int");

                    b.Property<int>("Ilosc_towaru_wyjscowego")
                        .HasColumnType("int");

                    b.Property<int?>("Kierownik_zmianyId")
                        .HasColumnType("int");

                    b.HasKey("Id_partii");

                    b.HasIndex("Kierownik_zmianyId");

                    b.ToTable("Produktownia");
                });

            modelBuilder.Entity("Projekt2.Models.Silos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data_skladowania")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_operacji")
                        .HasColumnType("int");

                    b.Property<int>("Ilosc_cukru")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Silos");
                });

            modelBuilder.Entity("Projekt2.Models.Silos_pakownia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data_pobrania")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_operacji")
                        .HasColumnType("int");

                    b.Property<int>("Id_partii")
                        .HasColumnType("int");

                    b.Property<int>("Ilosc_cukru_pobrana")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Silos_pakownia");
                });

            modelBuilder.Entity("Projekt2.Models.Sprzedarz", b =>
                {
                    b.Property<int>("Id_transakcji")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_transakcji"));

                    b.Property<DateTime>("Data_odbioru")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_kupca")
                        .HasColumnType("int");

                    b.Property<int>("Ilosc_opakowan")
                        .HasColumnType("int");

                    b.Property<int?>("KupiecId_kupca")
                        .HasColumnType("int");

                    b.HasKey("Id_transakcji");

                    b.HasIndex("KupiecId_kupca");

                    b.ToTable("Sprzedarz");
                });

            modelBuilder.Entity("Projekt2.Models.Stanowiska", b =>
                {
                    b.Property<int>("Id_stanowiska")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_stanowiska"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_stanowiska");

                    b.ToTable("Stanowiska");
                });

            modelBuilder.Entity("Projekt2.Models.Dostawy", b =>
                {
                    b.HasOne("Projekt2.Models.Dostawcy", "Dostawca")
                        .WithMany("Dostawy")
                        .HasForeignKey("DostawcaId");

                    b.Navigation("Dostawca");
                });

            modelBuilder.Entity("Projekt2.Models.Magazyn_sprzedarz", b =>
                {
                    b.HasOne("Projekt2.Models.Magazyn", "Operacja")
                        .WithMany()
                        .HasForeignKey("OperacjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projekt2.Models.Sprzedarz", "Transakcja")
                        .WithMany()
                        .HasForeignKey("TransakcjaId_transakcji");

                    b.Navigation("Operacja");

                    b.Navigation("Transakcja");
                });

            modelBuilder.Entity("Projekt2.Models.Pakownia", b =>
                {
                    b.HasOne("Projekt2.Models.Pracownicy", "Kierownik_zmiany")
                        .WithMany("Zmiany_pak")
                        .HasForeignKey("Kierownik_zmianyId");

                    b.Navigation("Kierownik_zmiany");
                });

            modelBuilder.Entity("Projekt2.Models.Pracownicy", b =>
                {
                    b.HasOne("Projekt2.Models.Dzialy", "Dzial")
                        .WithMany("Pracownicy")
                        .HasForeignKey("DzialId_dzialu");

                    b.HasOne("Projekt2.Models.Stanowiska", "Stanowisko")
                        .WithMany("Pracownicy")
                        .HasForeignKey("StanowiskoId_stanowiska");

                    b.Navigation("Dzial");

                    b.Navigation("Stanowisko");
                });

            modelBuilder.Entity("Projekt2.Models.Produktownia", b =>
                {
                    b.HasOne("Projekt2.Models.Pracownicy", "Kierownik_zmiany")
                        .WithMany("Zmiany_prod")
                        .HasForeignKey("Kierownik_zmianyId");

                    b.Navigation("Kierownik_zmiany");
                });

            modelBuilder.Entity("Projekt2.Models.Sprzedarz", b =>
                {
                    b.HasOne("Projekt2.Models.Kupcy", "Kupiec")
                        .WithMany("Transakcje")
                        .HasForeignKey("KupiecId_kupca");

                    b.Navigation("Kupiec");
                });

            modelBuilder.Entity("Projekt2.Models.Dostawcy", b =>
                {
                    b.Navigation("Dostawy");
                });

            modelBuilder.Entity("Projekt2.Models.Dzialy", b =>
                {
                    b.Navigation("Pracownicy");
                });

            modelBuilder.Entity("Projekt2.Models.Kupcy", b =>
                {
                    b.Navigation("Transakcje");
                });

            modelBuilder.Entity("Projekt2.Models.Pracownicy", b =>
                {
                    b.Navigation("Zmiany_pak");

                    b.Navigation("Zmiany_prod");
                });

            modelBuilder.Entity("Projekt2.Models.Stanowiska", b =>
                {
                    b.Navigation("Pracownicy");
                });
#pragma warning restore 612, 618
        }
    }
}
